services:
  web:
    build: docker/apache
    volumes: [ ./src:/var/www/html ]
    ports: [ 8080:80 ]
  db:
    build: docker/mysql
    volumes: [ mysql-practiceDocker:/var/lib/mysql ]

volumes:
  mysql-practiceDocker:
